---
- name: Download gitreceive
  command: chdir=/usr/local/bin wget https://raw.github.com/progrium/gitreceive/master/gitreceive

- name: Make gitreceive executable
  file: path=/usr/local/bin/gitreceive mode=0755

- name: Init gitreceive
  command: gitreceive init

- name: Copy receiver script
  template: src=receiver.sh
            dest=/home/git/receiver

- name: Copy database.yml template
  template: src=database.yml
            dest=/home/git/database.yml

- name: Copy load_torquebox_env.rb template
  template: src=load_torquebox_env.rb
            dest=/home/git/load_torquebox_env.rb

- name: Add user public keys
  script: enable-user.sh {{ item }}
  with_items: bootstrap.user_keys